### ISSUE TITLE
Still left to do

### ISSUE THREAD

**Issue by tomatogrove** [tomatogrove/ICS372-Assignment1#4]
Lets try and get this stuff done so by latest Tuesday night I can see how these changes affect Main, make those changes and turn in the zip!

Dealership + Vehicle:
-change vehicleID and dealershipID to string

DealerGroup:
-change Dealership[] to List<Dealership>
-add DealerGroup constructor 
-add void addIncomingVehicles(List<Vehicle>) method 
-change getDealer method to return a specific Dealer. Dealership getDealer(String dealershipID)
-remove exportDealerVehicles method

VehicleJsonParser:
-change buildMap to return Vehicles instead of Objects. May be easier to return List<Vehicle> rather than map but as long as the vehicles can be accessed that's all thats needed

**Comment by CwongM** [comment]
Adjusted dealerID field to a String data type

**Comment by tomatogrove** [comment]
Just realized we also still need a class diagram.. maybe should be assigned to me since ill be turning in the final project?

**Comment by CwongM** [comment]
I can't recall if we decided on who should do it last class meeting. But let me know if you need help with putting it together!

**Comment by tomatogrove** [comment]
Okay I'll keep that in mind!
